import math
print("Sine of 30 degrees:", math.sin(math.radians(30)))
print("Cosine of 60 degrees:", math.cos(math.radians(60)))
print("Tangent of 45 degrees:", math.tan(math.radians(45)))
print("Exponential of 2:", math.exp(2))
print("Natural Logarithm of 10:", math.log(10))
print("Square Root of 16:", math.sqrt(16))
print("2 raised to the power of 3:", math.pow(2, 3))
print("Ceiling of 4.7:", math.ceil(4.7))
print("Floor of 4.7:", math.floor(4.7))
